import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from 'next/head'
import Link from "next/link";
import { useEffect } from "react";
import { useState } from "react"
import Message from "../components/post/Message";
import { db } from "../utils/firebase"

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshort) => {
      setAllPosts(snapshort.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    });

    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, [])
  useEffect(() => {
    console.log("allPosts", allPosts);
  }, [allPosts])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="my-12 text-lg font-medium">
        <h2>
          Seen what other people are saying
        </h2>
        {
          allPosts.map(post =>
            <Message {...post}>
              <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
                <button >
                  {post?.comments?.length || 0}{" "}
                  comments
                </button>
              </Link>
            </Message>
          )
        }
      </main>

    </div>
  )
}
